spring:
  jackson:
    default-property-inclusion: non_null

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/eclinic_db
    username: appuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
